FREEOBJS=\
lib/stdio/printf.o \
lib/stdio/putchar.o \
lib/stdio/getchar.o \
lib/stdio/gets.o \
lib/stdio/puts.o \
lib/stdlib/abort.o \
lib/string/memcmp.o \
lib/string/memcpy.o \
lib/string/memmove.o \
lib/string/memset.o \
lib/string/strlen.o