KERNEL_ARCH_CFLAGS=
KERNEL_ARCH_CPPFLAGS=
KERNEL_ARCH_LDFLAGS=
KERNEL_ARCH_LIBS=

KERNEL_ARCH_OBJS=\
$(ARCHDIR)/boot.o \
$(ARCHDIR)/tty.o \
$(ARCHDIR)/gdt.o \
$(ARCHDIR)/gdt_flush.o \
$(ARCHDIR)/paging.o \
$(ARCHDIR)/ports.o \
$(ARCHDIR)/setup.o \
$(ARCHDIR)/v86.o \
$(ARCHDIR)/debug.o \
$(ARCHDIR)/paging_asm.o